set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CXX_FLAGS /bigobj)
set(VCPKG_C_FLAGS /bigobj)
set(VCPKG_CXX_FLAGS_RELEASE /favor:INTEL64)
set(VCPKG_C_FLAGS_RELEASE /favor:INTEL64)
